### ISSUE TITLE
add support for angular universal

### ISSUE THREAD

**Issue by muradm** [7leads/ngx-cookie-service#10]
Proposed change is to add `CookieServiceModule` with two static methods `forBrowser()` and `forServer()` where each will provide instance based on `Document` and `Request` respectively. Provided `CookieService` will work in the same way in both environments. Above static methods can be used in `BrowserAppModule` and `ServerAppModule` respectively providing same interface different implementations.

**Comment by CunningFatalist** [comment]
Hello, it's a good idea and still on our radar. However, there's already an issue for that: #1
