### ISSUE TITLE
Can't resolve all parameters for CookieService: (?)

### ISSUE THREAD

**Issue by ahmadlinus** [7leads/ngx-cookie-service#14]
## Expected Behavior
I had Cookie Service integrated in my project and it worked fine. It should work now because nothing has changed. 

## Actual Behavior
What actually happens is that when running ionic serve I get this peculiar error "Can't resolve all parameters for CookieService: (?). It does not run. It's very annoying and weird why it even keeps the project from starting... Maybe it's not something wrong with the Cookie Service itself, but I can't get to run my project anyway. 

## Steps to Reproduce the Problem
...

## Specifications

  - Version: Angular CLI/Core 4.1.3, Node 8.9, Ionic 3, ngx-cookie-serve 1.0.9
  - Browser: Safari
  - ...

**Comment by CunningFatalist** [comment]
Hi.

This is indeed strange. As this seems to be the most popular cause of bugs these days, maybe you should try

```bash
rm -rf node_modules
yarn # or npm install
```

or

```bash
yarn upgrade
```

before you do anything else.

I haven't really worked with Ionic before, so maybe it'd make sense to open a topic in their help forum or ask a StackOverflow question. If you can trace this bug back to this cookie service, feel free to open another issues. 

Thanks and good luck with your bug hunt


PS: To me it looks like some kind of problem with dependency injection, but that's just a guess

**Comment by tleperou** [comment]
Migrating from 7 to 8; `rm` of the `node_modules` magically worked for me.
