### ISSUE TITLE
Error: No Exported member Opaque Token. 

### ISSUE THREAD

**Issue by tarunguddeti** [7leads/ngx-cookie-service#15]
I have updated my angular version 4 to 5 . Have got an issue with ngx-cookie npm module. Becase of that I am now trying to install ngx-cookie-service module which gives me the same error. 
Below is my package.json and the error. 
Can someone please help me out as it is urgent. Thank you ! 

**Error:**

ERROR in node_modules/@rewardle/core/node_modules/ngx-cookie/src/cookie-options-provider.d.ts(1,20): error TS2305: Module '"C:/Users/Developer1/Tarunprojects/angularportals/rewardle.boilerplate.portal/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.

**My Package.json:**

{
  "name": "rewardle.boilerplate.portal",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test --browsers=Chrome",
    "test:ci": "ng test --browsers=Headless_Chrome --code-coverage=true --single-run=true",
    "lint": "ng lint --type-check",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@rewardle/core": "1.6.159",
    "angular-in-memory-web-api": "^0.3.1",
    "angular2-materialize": "^6.7.2",
    "angular2-moment": "^1.4.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^2.2.4",
    "json-typescript-mapper": "^1.1.3",
    "materialize-css": "^0.98.2",
    "moment": "^2.18.1",
    "ng-pick-datetime": "^4.2.3",
    "ng2-completer": "^1.5.2",
    "ngx-cookie-service": "1.0.10",
    "ngx-papaparse": "^1.2.2",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.5.2",
    "zone.js": "^0.7.8"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.6",
    "@angular/compiler-cli": "^5.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^7.0.12",
    "codelyzer": "^3.1.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "^3.0.2",
    "tslint": "^5.0.0",
    "typescript": "2.4.2"
  }
}

**Comment by CunningFatalist** [comment]
Hello, 

I am afraid this is not the right place to ask for help. We will gladly try to fix any bugs you encounter, but this is an integration problem. Therefore, the best thing you can do is ask this question over at [StackOverflow](https://stackoverflow.com/). As a general rule of thumb, try

```bash
rm -rf node_modules // don't know the Windows command for this, I'm sorry
yarn
```

whenever you encounter strange behavior such as this. It sounds odd, I know, but this fixes many bugs.

Good luck with you bug hunt!

Cheers
