### ISSUE TITLE
make `set()` configurations a single options object

### ISSUE THREAD

**Issue by odahcam** [7leads/ngx-cookie-service#16]
## Expected Behavior
I want to change my path: `set( 'x', 'y', <don't wanna change>, 'path/to' )` 

## Actual Behavior
~I can't do that.~

@CunningFatalist says that's possible trought:  `set( 'x', 'y', null, 'path/to' )` 

## Example 
`set( 'x', 'y', { path: '/', ... } )`

**Comment by CunningFatalist** [comment]
Hey there!

You should be able to simply set the parameter you do not want to change to `null` or `undefined` (the service is checking for truthiness in the `set` method). Adding overload to our API is something we are discussing right now, it sounds like a nice feature.

Cheers

**Comment by CunningFatalist** [comment]
Hello,

we discussed this again and are not going to implement this in the near future. We consider it best practice to always define a path and do not want to introduce possible new bugs.

Cheers

**Comment by odahcam** [comment]
All right, as long as we still have optional arguments, there's hope. 

![](https://media.giphy.com/media/l2JJyxPh3hWhQh05O/giphy.gif)
