### ISSUE TITLE
CSRF token not appending

### ISSUE THREAD

**Issue by HARIPRASADHARI** [7leads/ngx-cookie-service#17]
## Expected Behavior
CSRF token is added to Request header (POST) except login

## Actual Behavior
CSRF roken is not appending in request header.But it sending empty value

## Steps to Reproduce the Problem

Use Angular 4+,Django 2.7.6 try to hit from your local machine

## Specifications

  - Version:Version 63.0.3239.84 (Official Build) (64-bit)

  - Browser: Chrome 
I attached some screen shot for your reference as well as code i try to fetch csrf and append.

[https://www.codingforentrepreneurs.com/blog/jwt-token-interceptor-for-http-angular/
![giterror](https://user-images.githubusercontent.com/10670604/35972899-74636b18-0cf9-11e8-9667-e829bc2cb888.png)
![git](https://user-images.githubusercontent.com/10670604/35972977-c489a45e-0cf9-11e8-8dd0-1dcfb17d7854.png)

](url)
Thank you in advance

**Comment by CunningFatalist** [comment]
Hello there,

we have just discussed your issue, but I think we won't be able to help you with that. First, it's not obvious how your question is tied to our package. Then, it seems to be an integration problem and not a problem with the cookie service itself. Therefore, you should probably open an issue over at StackOverflow.

Good luck with your bug hunt!

Cheers
