### ISSUE TITLE
Springboot JSESSIONID in auth service

### ISSUE THREAD

**Issue by TENDesign** [7leads/ngx-cookie-service#18]
## Expected Behavior
check JSESSIONID cookie

## Actual Behavior
returns false even though the cookie exists

## Steps to Reproduce the Problem

I am trying to setup an Auth service to check if a JSESSIONID cookie exists or has been created by Springboot. My service looks like this:

```
import { Injectable } from '@angular/core';
import { CookieService } from 'ngx-cookie-service';

@Injectable()
export class AuthService {

    constructor(
        private cookieService: CookieService
    ) {}

    get isLoggedIn() {
        this.cookieService.set( 'test', 'Hello World' );
        const jsession = this.cookieService.check('JSESSIONID');
        console.log(jsession);
        if (!jsession) {
            return false;
        } else {
            return true;
        }
    }

    get isAdmin() {
        return true;
    }

    get isManager() {
        return false;
    }

    get userLang() {
        return 'en';
    }

}
```
I am able to confirm that the session cookie does in fact exist, however neither  `const jsession = this.cookieService.check('JSESSIONID');`, `getAll()`, or `get()` seem to see the cookie?

**Comment by CunningFatalist** [comment]
Hello,

I fear that this is not the right place for your question. It looks like an implementation problem and should therefore be posted over at [StackOverflow](https://stackoverflow.com/). However, I have had a look at your code and if this is indeed the real code you are using, you may want to programmatically check if the `test` cookie exists. Furthermore, you should check in your real browser, if a cookie with the ID `JSESSIONID` actually exists (or if it uses another key).

Good luck with your bug hunt :)

**Comment by webcat12345** [comment]
I am having the same issue with `JSESSIONID`. Tested with `test` cookie and it works, but even `getAll()` function does not return `JSESSIONID`.

**Comment by webcat12345** [comment]
I just noticed that `JSESSIONID` is secured (httpOnly), it means I can't access to this value.
