### ISSUE TITLE
getAll() returns an empty object, even though there are cookies present.

### ISSUE THREAD

**Issue by filipbarak** [7leads/ngx-cookie-service#19]
## Expected Behavior
this.cookieService.getAll() should return the cookies that are locally stored.
The cookies are set from my server via passport and session.

## Actual Behavior
this.cookieService.getAll() returns {}

## Steps to Reproduce the Problem
call .getAll() method on the cookie service.

## Specifications

  - Version: ^1.0.10
  - Browser: Chrome 64.0.3282.186 (Official Build) (64-bit)

Here are some screenshots and code snippets:
```

 getAllCookies() {
    console.log(this.cookieService.getAll()); //returns an empty object {}
  }
<button (click)="getAllCookies()">getAllCookies</button>


```

Proof that I have cookies stored:

http://prntscr.com/ijv4cs < the cookies

http://prntscr.com/ijv4pv < when I click getAll(). 

Is this a problem on my side, or this issue is valid? 

Thanks.

**Comment by CunningFatalist** [comment]
Hey,

others have had similar issues and thus far it has usually been an implementation issue. Sadly, we cannot help you with those (StackOverflow is a better place for that), but we cannot absolutely rule out the possibility that it's a problem with our service. However, here some recommendations on how to proceed. Maybe they will help you.

First, you should check out the following SO answers:

* https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain
* https://stackoverflow.com/questions/8064318/how-to-read-a-secure-cookie-using-javascript 
* https://stackoverflow.com/questions/15914744/javascript-document-cookie-always-empty-string

Alternatively, you can try setting an explicit path and getting your cookie from it (this solves a good bunch of all cookie-service/package/plugin related problems out there). Also, check if the domains are correct. 

As a last resort, check manually `document.cookie`. Maybe you can find something there.

If this is really a problem with our service, feel free to supply an environment or tests that help us reproduce the issue (that saves us a lot of time, which is great 👍 ).

Good luck with your bug hunt!
