### ISSUE TITLE
Deleting cookies: All paths & domains

### ISSUE THREAD

**Issue by mustafaekim** [7leads/ngx-cookie-service#2]
Whe I try to delete a cookie by simple delete method, it does not work. I think it requires to the path & domain also.

```ts
this.cookieService.delete("auth_token");
```

thus, I need to write:
```ts
this.cookieService.delete("auth_token", "/", "quizcv.com");
this.cookieService.delete("auth_token", "/", "www.quizcv.com");
this.cookieService.delete("auth_token", "/", "localhost");
```
which is very uncomfortable. Moreover, there are some combinations with different paths. 

How can I delete all cookies, whatever the path or domain is?

**Comment by mustafaekim** [comment]
Note: If **get** method would not return a string but an object with path & domain of the cookie, I would be able to delete all the cookies because I would know their path & domains

**Comment by badcoder28** [comment]
Had the same issue deleting cookies with deleteAll() method it doesn't work either

**Comment by jeeva-nikam** [comment]
No need to add domain it worked for me like this...
this.cookieService.delete('myCookie', ' / ');

**Comment by paroe** [comment]
The browser (and therefore the cookie-service) simply just have no way of knowing the paths and domains of the set cookies. For security reasons, they can only access the cookies of the current path and domain.

[Here](https://stackoverflow.com/questions/17776975/how-do-i-delete-a-cookie-from-a-specific-domain-using-javascript) you can find a good explanation of the issue:

> For security, you’re not allowed to edit (or delete) a cookie on another site. Since there’s no guarantee that you own both foo.domain.com and bar.domain.com, you won’t be allowed to edit the cookies of foo.domain.com from bar.domain.com and vice versa.

The only thing you can do is to take an educated guess, like in [this attempt](https://stackoverflow.com/a/5886746/1007003).

**Comment by sahajrajmalla** [comment]
I have same problem!

**Comment by rajibhalder** [comment]
I have the same problem as my frontend server hosted on abc.com but api server hosted on xyz.com server. When log out, I want to delete all cookies (e.g accessToken, JSESSIONID) of xyz.com also.
