### ISSUE TITLE
How to get ALL cookies from browser for current domain?

### ISSUE THREAD

**Issue by TakhirMamirov** [7leads/ngx-cookie-service#20]
I used the latest version of the service and tried to get all cookies that I see in browser's request. While my backend sends several cookies, I see just a few of them. How can I extract all cookies, not only those I set via set() method?

**Comment by elnunga25** [comment]
Hello TakhirMamirov,
Have you found a workaround?
I have the same issue.

**Comment by TakhirMamirov** [comment]
Nope, I resolved the initial issue without need to having all those cookies.

**Comment by astechnolabs-html** [comment]
it's 3 year of this question, still having same issue.

**Comment by pavankjadda** [comment]
> it's 3 year of this question, still having same issue.

You can use `getAll()` method
