### ISSUE TITLE
How do I mock this for testing?

### ISSUE THREAD

**Issue by buddyackerman** [7leads/ngx-cookie-service#21]
How/where do I setup/mock cookies for the cookie service to read?  I don't really want to create an entire mock class of my own if I don't have to.

**Comment by CunningFatalist** [comment]
Hello there!

How and where you mock cookies is up to your and/or your testing framework of choice. I would suggest checking out [some of these resources](https://www.google.de/search?ei=ZDDLWtyKE8GiwAL88J3gCg&q=mock+cookies+javascript&oq=mock+cookies+javascript&gs_l=psy-ab.3..0i22i30k1.2227.3842.0.4034.11.11.0.0.0.0.111.859.8j2.10.0....0...1.1.64.psy-ab..1.10.858...0i19k1j0i22i30i19k1.0.Pqeh5MZLfUM), or creating a [Jasmine Spy](https://jasmine.github.io/api/2.6/Spy.html) for the service (if you're using Jasmine, that is). ([Here's how to do that.](https://stackoverflow.com/questions/30658525/spy-on-a-service-method-call-using-jasmine-spies))

Cheers
