### ISSUE TITLE
This module does not work with `ng test`

### ISSUE THREAD

**Issue by dolanmiu** [7leads/ngx-cookie-service#25]
## Expected Behavior
Test Pass

## Actual Behavior
Error `Unexpected token import`

## Steps to Reproduce the Problem
Run `ng test` on a component you are trying to test which uses this library

## Specifications

  - Version: Angular 5
  - Browser: N/A

**Comment by sharmaprashant232** [comment]
same issue with me

**Comment by CunningFatalist** [comment]
Hello there!

Your error message looks like a syntax error, you should google for it. However, I created an NG 5 + 6 demo app and added some cookie tests to them, just to be 100% sure. They worked.

Cheers and good luck with your bug hunt

PS: If you are unsure about the syntax or the imports you need, you may check out the tests we have here in this repository: https://github.com/7leads/ngx-cookie-service/blob/master/demo-app/app/app.component.spec.ts
