### ISSUE TITLE
Intermittant Access to set cookies

### ISSUE THREAD

**Issue by nzjemountfort** [7leads/ngx-cookie-service#27]
Here's an example - Hoping to have some insight into why it may be doing this, whether there is a setting I can change to stop it, but I suspect it is a bug

1. So I set a few cookies in a login process (sets the cookie fine)
2. I'm on a URL like /account/settings -> I hit refresh - the cookie doesn't exist
3. I then navigate to another page -> like /account/XXX/XXX/XXX -> and hit refresh - the cookie re-appears again

I could do a screen cast to show the problem - it is very strange

**Comment by CunningFatalist** [comment]
Hello there,

this looks very much like an implementation problem to me. You should open a [StackOverflow question](https://stackoverflow.com/questions/ask) and supply real code there. From what you are describing, I can only take an educated guess... but I think you should double-check your cookie domains.

Good luck with your bug hunt, let us know if (and how) you were able to solve your problem.

Cheers

**Comment by nzjemountfort** [comment]
Hey there, I finally managed to spot what is/was causing this - and i'm not sure if this might be something your aware of, not sure what the core library does.

So here's the scenario that was causing it

In angular i have a router/interceptor that redirects a user to /login if the cookie values aren't present, so the issue was the following
-> I would load url like {a}/{b}/{c} (not logged in)
-> i would be redirected to /login
-> then when i login for some reason the cookie path would be set to {a}/{b}/{c} (but the url in the address bar is most certainly /login)

Basically had 6-7 different path/duplications of the same cookies (and i could be logged in as like 3-4 different id's within different sections - it was causing all sorts of nightmare overrides / and problems logging out)

The solution was setting path in the cookie.set(name,val,exp,'/' .... ) so that when i 'logout' it definitely would destroy the cookie sets that the login check was looking for.

I would have thought path would have by default been '/' ?

So worth making a note (in angular 4+)
That i'm unsure how it was ever picking up the previous url (prior to redirect)
Unless angular 4 has some url masking going on so while i see /login up the top - the cookie service is looking at the previous URL

Posting this reply up here, just incase it's worth looking into your end - but it's more than likely an angular implementation remark.
