### ISSUE TITLE
Cookies not getting set

### ISSUE THREAD

**Issue by nicolaspierre1990** [7leads/ngx-cookie-service#28]
## Expected Behavior
Cookie being set

## Actual Behavior
No cookie being set

## Steps to Reproduce the Problem
What i'm trying to do is to store a JWT token in a cookie using following code.
` setCookie(name: string, value: string, encrypt: boolean, days?: number) {
        let date = null;
        if (days) {
            date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        }

        if(encrypt){
            value = btoa(value);
        }

        this.cookie.set(name, value, date, "/", environment.domain, true);
    }`

but the cookie is not getting created. I stept into the code of the plugin and no errors happen there.

## Specifications

  - Version: Angular 6
  - Host: LocalHost and deployed version

**Comment by andreas-harmuth** [comment]
I have the same problem with same specifications.

**Comment by phoude** [comment]
I have problem where cookie values are not persisted in IE or Edge. Still investigating what could be causing it...

**Comment by phoude** [comment]
I have done further testing and it looks like there is an inherent problem with how cookies are read back when used in conjunction with an Angular router. I don't know how to resolve this other than by explicitly setting the path to "/". It does not work otherwise with a different path as described in my [stackoverflow post](https://stackoverflow.com/questions/51054135/angular-router-cookie-path).

**Comment by azhararmar** [comment]
Same here with Angular7, it works when the path is set to "/" otherwise it doesn't

**Comment by cyphercodes96** [comment]
Same here, been facing this issue recently with `.localhost` as domain
        this.cookieService.set('currentUser_email', email, undefined, '/', '.' + cookieDomain.toString());
        console.log(cookieDomain.toString()); // localhost, attempting to set domain to .localhost
        console.log(this.cookieService.getAll()); // {} empty object
        console.log(this.cookieService.check('currentUser_id')); // false

**Comment by Shubham-Kul** [comment]
just do like this
this.cookieService.set('categoryName', category.name, 365, '/');
It will solve your problem
