### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by vtkumaresan** [7leads/ngx-cookie-service#29]
In Angular 6, got below error

ERROR in ../node_modules/ngx-cookie-service/cookie-service/cookie.service.js
Module not found: Error: Can't resolve '@angular/common' in '/node_modules/ngx-cookie-service/cookie-service'
ERROR in ../node_modules/ngx-cookie-service/cookie-service/cookie.service.js
Module not found: Error: Can't resolve '@angular/core' in '/node_modules/ngx-cookie-service/cookie-service'

**Comment by lzk1994** [comment]
@vtkumaresan Friend, is this problem solved?

**Comment by vtkumaresan** [comment]
yes, its resolved.

**Comment by lzk1994** [comment]
@vtkumaresan How can I achieve this? If I introduce ngx-cookie-service into angular6, the project will not be able to run. Is it still not compatible with angular6?

**Comment by PixeliGer** [comment]
@vtkumaresan So, whats the solution, I still have problems with my Angular 6 project

**Comment by CunningFatalist** [comment]
Hey guys,

we have answers to common issues [here](https://github.com/7leads/ngx-cookie-service#faq) and [here](https://github.com/7leads/ngx-cookie-service#i-am-always-getting-a-token-missing-or-no-provider-error).

I just wanted to leave that here, because it might help some people.

Cheers
