### ISSUE TITLE
Angular Universal SSR rendering problem

### ISSUE THREAD

**Issue by samialmorshedi** [7leads/ngx-cookie-service#30]
`ERROR Error: NotYetImplemented` is the error I got and it mentioned something such as "at CookieService.check" and "at CookieService.get". How can I fix it?

**Comment by CunningFatalist** [comment]
Hey!

We currently do not support SSR. [But there's already an issue for that](https://github.com/7leads/ngx-cookie-service/issues/1). If you happen to  know some things about SSR, feel free to create a PR! 

Cheers
