### ISSUE TITLE
Delete functionality not working in Safari 

### ISSUE THREAD

**Issue by ahmadimt** [7leads/ngx-cookie-service#34]
## Expected Behavior
`cookieService.delete('token');` and `cookieService.deleteAll('token');` should delete the cookies with name `token` irrespective of browser.

## Actual Behavior
This is working on Chrome but it is not on Safari browser. However, `cookieService.deleteAll();` works on both the browsers.
## Steps to Reproduce the Problem

I have create a project to reproduce the same on Github.

https://github.com/ahmadimt/ngx-cookie-bug

## Specifications

  - ngx-cookie-service Version: 1.0.10
  - Browser:  Safari Version 11.1.1 (13605.2.8)

**Comment by CunningFatalist** [comment]
Hello, 

I think there is a misunderstanding. Have a look at the methods `delete` and `deleteAll`:

```
delete( name: string, path?: string, domain?: string ): void;
deleteAll( path?: string, domain?: string ): void;
```

Delete all accepts a path, not a name.

I hope this helps you.

Cheers
