### ISSUE TITLE
Its only saving one array  with two object

### ISSUE THREAD

**Issue by tikemantns** [7leads/ngx-cookie-service#35]
this.cookieService.set( 'cart', JSON.stringify(this.addedItems));

var sssl = this.cookieService.get('cart');
sssl = JSON.stringify(sssl);
this.cartItems = JSON.parse(JSON.parse(sssl));
Stored Data Type
(2) [{…}, {…}]

**Comment by CunningFatalist** [comment]
Hello, 

I am not really sure how we could help you with this. It seems to be an implementation error, and not a bug of our package. You should probably post a question over at [StackOverflow](https://stackoverflow.com/), I am pretty sure someone there will be able to help you with this.

Cheers
