### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by abhishek-mittal** [7leads/ngx-cookie-service#36]
## Expected Behavior
should work during build in angular universal env
...

## Actual Behavior
in .../node_modules\ngx-cookie-service\index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './cookie-service/cookie.service';
throwing SyntaxError: **Unexpected token export**
...

## Steps to Reproduce the Problem
...

## Specifications
**Angular-Universal-App**
  - Version: ... 5.2.0

**Comment by CunningFatalist** [comment]
Hello,

we do not support Universal at the moment. See #1

Cheers
