### ISSUE TITLE
Angular 6 set cookie, get cookie  in Edge not working after routing

### ISSUE THREAD

**Issue by ShadowQueen** [7leads/ngx-cookie-service#37]
## Expected Behavior
Set cookie, try to get the cookie after routing. The cookie is not present in the browser.
It is somehow deleted. This is tested in Edge browser in Chrom everything is working.

## Actual Behavior
Expect to have the cookie after routing.
## Steps to Reproduce the Problem
Set cookie in the app component. Make some 'test' component, need a button on app component to route to the 'test' component, after routing, try to get the cookie.
I would make stackblitz example, but I am getting the error: pointing to non-existing "lib/index.ts" .

## Specifications

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.0
Node: 8.11.2
OS: win32 x64
Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0 (cli-only)
@angular-devkit/core         0.6.0 (cli-only)
@angular-devkit/schematics   0.6.0 (cli-only)
@schematics/angular          0.6.0 (cli-only)
@schematics/update           0.6.0 (cli-only)
rxjs                         6.1.0 (cli-only)

Browser: Edge

**Comment by stepanmas** [comment]
May be next code to [fix it](https://github.com/7leads/ngx-cookie-service/blob/1886b06af5b9cfcd20376918337ef937efa23bea/lib/cookie-service/cookie.service.ts#L118)?
```
if (domain && !(document.documentMode || /Edge/.test(navigator.userAgent))) {
  cookieString += 'domain=' + domain + ';';
}
```

**Comment by CunningFatalist** [comment]
Hello,

it is always best practice to define a path. Have a look at [this issue](https://github.com/7leads/ngx-cookie-service/issues/2) and our updated documentation [here](https://github.com/7leads/ngx-cookie-service).

Cheers
