### ISSUE TITLE
Support for Angular 5.x ?

### ISSUE THREAD

**Issue by MrBlaise** [7leads/ngx-cookie-service#4]
Hey!

Angular 5 is still in beta however (it will be released in a couple of days). Can you add support to it? The peer dependencies now restrict to version 4.

**Comment by CunningFatalist** [comment]
Hey there MrBlaise,

I updated the peer dependencies section of `package.json`. You can `npm install` the newest version of the cookie service now (1.0.9). 

Cheers from Berlin

PS: For whatever reason, I had to `rm -rf` my `node_modules` folder and run `npm install` again. However, all warnings seem to be gone now. I will now close this issue. If it does not work for you, please let us know 😀
