### ISSUE TITLE
Same Name diff domains.

### ISSUE THREAD

**Issue by JoellyR** [7leads/ngx-cookie-service#40]
## Expected Behavior
Not to sure.

## Actual Behavior
Want to clarify.

## Steps to Reproduce the Problem
Make a cookie with id foobar and domain as foo.bar.com, make a cookie with the domain set to bar.com, what would happen in this case? I couldn't seem to find any documentation on this. From my understanding i see a [issue in ng-cookie](https://github.com/salemdar/ngx-cookie/issues/60#issue-321896733).. not sure if it's related as this library is based off ng2-cookie not ng-cookie.
## Specifications

  - Version: N/A
  - Browser: N/A

**Comment by paroe** [comment]
The actual behavior seems to be not specified in any RFC, as far as i can tell. So the results may vary from browser to browser.
See also this [rather old link](https://www.sitepoint.com/3-things-about-cookies-you-may-not-know/)
