### ISSUE TITLE
How to set the cookie as an array cookie and keep on updating the array.

### ISSUE THREAD

**Issue by bhartendukumar12** [7leads/ngx-cookie-service#42]
I was able to set the cookie.I need to set the cookie as an array and want to keep updating that array.

Use Case:I have videos in my platform and I want to capture the watched video for not logged in 
                user.So each time user watches the video I want to update the cookie array with video ID ,so that 
                when the same user  visit my site next time , I will know what are the video which has been 
                watched by that particular user.

**Comment by paroe** [comment]
The cookie value has to be a string. So you should serialize them accordingly, preferrably using `JSON.stringify` and `JSON.parse` for the deserialization.
But beware that cookies must not exceed a certain size. According to [RFC6265](https://tools.ietf.org/html/rfc6265#section-6.1) they are limited to 4096 bytes.
You may want to use the [LocalStorage Api](https://developer.mozilla.org/de/docs/Web/API/Window/localStorage) or your application's server instead.
