### ISSUE TITLE
Delete cookie is not working in IE 11

### ISSUE THREAD

**Issue by hilarudeens** [7leads/ngx-cookie-service#43]
## Expected Behavior
(new CookieService()).delete('somename','/','example.com') is expected to delete cookie value which already in set.

## Actual Behaviour
Cookie is not getting delete.

## Steps to Reproduce the Problem

1. Write following code
```
(new CookieService()).delete('somename','/','yourdomain.com');
window.location.href = "http://somedoman.com"
```
2. Navigate back to some page which is in yourdomain.com

NOTE: This behaviour, i have noted in outlook addin development.

## Specifications

  - Version: ngx-cookie-service@1.0.10
  - Browser: IE 11 (Note: Found browser by using useragent in https://developers.whatismybrowser.com/useragents/parse/#parse-useragent) 
  - User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko

**Comment by CunningFatalist** [comment]
Hello,

I am afraid that cookies do not function this way. Have a look at @paroe's answer [here](https://github.com/7leads/ngx-cookie-service/issues/2#issuecomment-435603668).
