### ISSUE TITLE
#node dist/server.js

### ISSUE THREAD

**Issue by huwenjian** [7leads/ngx-cookie-service#46]
1 . angular5.1 -SSR 
2. node /dist/server.js 
3.error 
(function (exports, require, module, __filename, __dirname) { export * from './cookie-service/cookie.service';
                                                              ^^^^^^
SyntaxError: Unexpected token export

**Comment by CunningFatalist** [comment]
Hello,

please see #1. I am going to close this issue and mark it as a duplicate.

Cheers
