### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by julmot** [7leads/ngx-cookie-service#47]
Since there's no CHANGELOG.md and no releases or tags, where do I find information about changes in release v2?

**Comment by CunningFatalist** [comment]
Hello!

That is... true. Here you go: [CHANGELOG.md](https://github.com/7leads/ngx-cookie-service/blob/92b0cb51d8a014d2600cb13bcc29ab3977f747dc/CHANGELOG.md).

Cheers
