### ISSUE TITLE
Could not resolve ngx-cookie-service ...

### ISSUE THREAD

**Issue by vithubati** [7leads/ngx-cookie-service#49]
## Expected Behavior
... no error should be thrown as part of ng build

## Actual Behavior
... Could not resolve ngx-cookie-service relative 
 error TS2307: Cannot find module 'ngx-cookie-service'.
src/app/app.module.ts(22,29): error TS2307: Cannot find module 'ngx-cookie-service'.

## Steps to Reproduce the Problem
... install the latest ngx-cookie-service 

## Specifications

  - Version: ... 2.0.1
  - Browser: ...
  - ...
I was working perfectly fine until today after updating the package

**Comment by pschuster** [comment]
It worked for me fine and now I have exactly the same issue.

`ERROR in app/app.module.ts(321,5): Error during template compile of 'AppModule'
  Could not resolve ngx-cookie-service relative to [object Object]..
`

**Comment by pschuster** [comment]
I changed to version 2.0.1 (had 2.0.0) before and changed this line:

`import { CookieService } from 'ngx-cookie-service';`

into this:

`import { CookieService } from 'ngx-cookie-service/lib';`

Now It's working fine again. Not sure however, if that helps you...

**Comment by vithubati** [comment]
as a quick fix for my project, I installed the old version 2.0.0 and got it worked

**Comment by pschuster** [comment]
I was on 2.0.0 and it's not working anymore, tried 2.0.1 and now back on 2.0.0. It does not work.

```ERROR in app/app.module.ts(321,5): Error during template compile of 'AppModule'
  Could not resolve ngx-cookie-service relative to [object Object]..
src/app/service/user.service.ts(29,29): error TS2307: Cannot find module 'ngx-cookie-service'.
src/app/app.component.ts(13,29): error TS2307: Cannot find module 'ngx-cookie-service'.
src/app/app.module.ts(142,29): error TS2307: Cannot find module 'ngx-cookie-service'.
```

**Comment by pschuster** [comment]
As a quick fix it helped to add cookie.service.ts directly to my project. However, I would rather want to add the package via npm.

**Comment by CunningFatalist** [comment]
Hello,

thanks for the notification. There was an issue with the publishing script. 2.0.2 is out and should resolve the issue. I am very sorry for the inconvenience.

Cheers
