### ISSUE TITLE
skip encodeURIComponent for cookie name and value

### ISSUE THREAD

**Issue by faisalike** [7leads/ngx-cookie-service#56]
## Expected Behavior
...
this package automatically encode the string which i set
## Actual Behavior
...

## Steps to Reproduce the Problem
...
how to skip this encoding
## Specifications

  - Version: ...
  - Browser: ...
  - ...

**Comment by CunningFatalist** [comment]
Hello,

why would you want to skip this? We make sure that the cookie string is valid, that's what it's good for. Therefore, we do not plan to add an option to skip this.

Cheers

**Comment by faisalike** [comment]
I just want to read the cookie from backend but ngx cookie service change
"=" to "%3D"
So this is causing pain to change on backend site

**Comment by CunningFatalist** [comment]
Hello,

you can also decode URL strings on your backend. It shouldn't be that hard. 

For example, in PHP you can simply do:

```
echo urlencode('=');           // outputs %3D
echo urldecode('%3D');     // outputs =
```

Cheers

**Comment by Tonher31** [comment]
Hi, 

I am in the same situation. 
I need to have brackets in my cookie, because that's how it is done in the applcation. 
Besides, I have absolutely no control on the backend.

Is there really no way to skip the encoding ?

**Comment by faisalike** [comment]
No they said there is no way

**Comment by egorshulga** [comment]
@CunningFatalist we're in the same situation. We have no control over PHP part of our application. So we can't handle cookies with `[]` chars in it.
Could you reconsider your opinion?

**Comment by liangshen001** [comment]
+1
![image](https://user-images.githubusercontent.com/22604816/71873174-861b2e00-3159-11ea-8b62-24f987813a4c.png)
![image](https://user-images.githubusercontent.com/22604816/71873191-93381d00-3159-11ea-8ae4-aee2b5237e63.png)

**Comment by UnleashSpirit** [comment]
+1 needed for legacy application :(
others library offer this option

**Comment by illia108** [comment]
sorry, but it doesn't make sense. why do you make this decision? if I need to encode I encode. Now I need to change logic everywhere else.

**Comment by omkardixit** [comment]
+1 need ths. @illia108 which library did you switch to?

**Comment by illia108** [comment]
@omkardixit just created my own custom service with `get`, `set` and `remove` as I don't need anything else

**Comment by COLAMAroro** [comment]
Reviving this issue, because I have the exact same problem still.

I don't own the complete stack, and can't modify the backend.
