### ISSUE TITLE
Cookies don't show up if domain attribute has 2 (or more?) subdomain levels

### ISSUE THREAD

**Issue by alexvy86** [7leads/ngx-cookie-service#57]
This issue occurs when the `domain` attribute of a received cookie has 2 (or more, I assume) subdomain levels (e.g. `myCookie=myValue; domain=my.subdomain.domain.com; path=/`).

## Expected Behavior
`cookieService.get('myCookie')` or `cookieService.getAll()` return the cookies.

## Actual Behavior
`cookieService.get('myCookie')` return an empty string, and `cookieService.getAll()` is empty.

## Steps to Reproduce the Problem
Use `ngx-cookie-service` to retrieve a cookie that has a `domain` attribute with 2 (maybe more as well, I didn't test with more than 2) subdomain levels.

## Specifications

  - Version: ngx-cookie-service 1.0.10
  - Browser: Chrome 71.0.3578.98

**Comment by CunningFatalist** [comment]
Hey,

have you already checked out the actual `document.cookie` value? Can you retrieve the value manually? [Did you explicitly set the domain?](https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain) Did you eventually manage to debug the problem?

Cheers

PS: Sorry for the late answer. I am quite busy at the moment, and cookie service issues sadly have to wait.

**Comment by alexvy86** [comment]
Sorry for the late reply. This must have been a problem with a different part of our setup, I haven't tried to specifically reproduce it but right now everything's working fine with 2 subdomains. Since there are no other comments here I'll go ahead and close the issue.
