### ISSUE TITLE
this.cookieService.delete('TestCookie') is not working

### ISSUE THREAD

**Issue by Dhara-Openxcell** [7leads/ngx-cookie-service#58]
## Expected Behavior
I am working on Logout functionality in Angular 7 using ngx-cookie-service. Below is the code of my Logout() function. I am having issue in this.cookieService.delete('Cookie') function.

this.cookieService.delete('TestCookie');
console.log("cookie deleted!");

            if (this.cookieService.get('TestCookie') && this.cookieService.get('TestCookie') != null && this.cookieService.get('TestCookie') != '') {
                console.log("cookie found!");
            }  
            else{   
    
                console.log("cookie not found!");
    
                this.commonservice.logout().subscribe(
                    data => {
                        if (data.status == 200) {
                            console.log("logout data,",data);      
                        }
                    },
                    error => {
                        return Observable.throw(error);
                    }
                );
                console.log("navigate to login");
                this.router.navigate(['/login']);
            }      
        }

It should print "Cookie deleted" and then it should print "cookie not found!" and then logout method should be called

## Actual Behavior
Actually it is behaving as below:
"Cookie deleted! "is printed and then "cookie found" so the user is not logged out .
Even in Application i can see the cookie is remained as it is.

## Steps to Reproduce the Problem

please guide me through this problem,Thank you
## Specifications

  - Version: Angular 7, ngx-cookie-service : 2.1.0
  - Browser: Chrome

**Comment by CunningFatalist** [comment]
Hello,

this seems to be an implementation issue, and not an issue with the cookie service itself. You should post this over at [StackOverflow](https://stackoverflow.com/questions/ask) and provide more information such as 

- the part of your code where you delete the cookie
- the return value of `this.cookieService.get('TestCookie')`

If this is actually a bug of ours, feel free to open another issue 👍 

Cheers

**Comment by Dhara-Openxcell** [comment]
Thanks a lot for your response!

**Comment by CunningFatalist** [comment]
You're welcome 😃
