### ISSUE TITLE
Domain && 

### ISSUE THREAD

**Issue by cyphercodes96** [7leads/ngx-cookie-service#59]
I have two different environments, staging and production.
Domains: `staging.ccdev.com` && `ccdev.com`
I have cookies registered under both domains, as `.staging.ccdev.com` && `.ccdev.com`
## Expected Behavior
...
when on staging, `staging.ccdev.com`, 
cookieService.get('cookie') to fetch `cookie` under current domain (`staging.ccdev.com`)
## Actual Behavior
...
the cookieService fetches the cookie of `.ccdev.com`

## Steps to Reproduce the Problem
...
Get an application running, that works on two different domains, one for staging, one for production.
only difference, is having the staging as a subdomain for production.

Also when I simply attempt to `cookieService.deleteAll('/');` so that I would delete the cookies that are not required, so that the `cookieService.get('cookie')` is forced to fetch the cookie I want under current domain, it doesn't delete the cookies for `.ccdev.com`

**Comment by CunningFatalist** [comment]
Hello,

please check out this issue: https://github.com/7leads/ngx-cookie-service/issues/57

Cheers

**Comment by cyphercodes96** [comment]
These are two different issues.

You didn't even take the time to understand my use-case + labeled issue as `closed`

obviously you don't have the time nor dedication for this package.

Take care.
