### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by jmblank09** [7leads/ngx-cookie-service#6]
When i'm injecting the cookieService to another service it gets an error like this when requesting an http method
<img width="645" alt="screen shot 2017-11-21 at 6 54 20 am" src="https://user-images.githubusercontent.com/21171734/33045738-de6aca7e-ce88-11e7-88ec-8aa83b35d3c5.png">

This is my code
```
import { Injectable } from '@angular/core';
import { Http, Response } from "@angular/http";

import { Observable } from "rxjs/Rx";
import { tokenNotExpired } from 'angular2-jwt';
import { UtilService } from "../services";
import { CookieService } from 'ngx-cookie-service';

@Injectable()
export class AuthService {
  Http;

  static parameters = [Http];
  constructor (
    private http: Http,
    private util: UtilService,
    private _cookieService: CookieService
  ) {
    this.Http = http;
  }

  // authenticates the user
  authenticate(data) {
    console.log(this._cookieService.get('company'), 'hereree')
    var body = {
      email: data.username,
      password: data.password,
      // company_slug: this._cookieService('company').get || ''
    }

    return this.Http.post('/api/users/session', body)
    .map((data: Response) => data.json())
    .catch(this.handleError);;
  }

  // check if the user's token is not expired
  loggedIn(token) {
    return tokenNotExpired(null, token);
  }

  // Remove the user's data
  logout() {
    this.util.deleteAllCookieData()
  }

  private handleError (error: any) {
    return Observable.throw(error.json());
  }
}
```

**Comment by nithinshiriya** [comment]
Even I am facing the same is issue Can not read property get.

**Comment by CunningFatalist** [comment]
Hello there,

I've had a look at your code, and I doubt that this is a problem with `ngx-cookie-service`. I think you are having a different problem, either with dependency injection or with the following line:

```typescript
// company_slug: this._cookieService('company').get || ''
```

This should be

```typescript
company_slug: this._cookieService.get('company') || ''
```

If that does not help you, check out StackOverflow questions concerning Angular (2+) and dependency injection. For example: https://stackoverflow.com/questions/42956852/angular-2-injected-service-is-undefined

I hope this helps you.

Cheers from Berlin

**Comment by jmblank09** [comment]
I only commented because it is not working.
