### ISSUE TITLE
Improve set API for how to set the value of optional parameter

### ISSUE THREAD

**Issue by longgt** [7leads/ngx-cookie-service#61]
set API is defined too much parameters.
It's hard to skip optional and only focus on parameter that I want.

## Actual Behavior
set( name: string, value: string, expires?: number | Date, path?: string, domain?: string, secure?: boolean, sameSite?: 'Lax' | 'Strict' ): void;

If I need only to set sameSite and skip other options, I'll to call something like the following
```
set('foo', 'fooValue', null, null, null, false, 'Lax');
```

## Expected Behavior

It should be
```
set('foo', 'fooValue', { sameSite: 'Lax'});
```

## Specifications

  - Version: 2.1.0

**Comment by CunningFatalist** [comment]
Hello,

there is already a pull request by @alessioferrero in the works: https://github.com/7leads/ngx-cookie-service/pull/53 😃 

Cheers
