### ISSUE TITLE
ngx-cookie-service not deleting cookie on ngOnInit and ngOnDestroy

### ISSUE THREAD

**Issue by RanjithRanaRudra** [7leads/ngx-cookie-service#62]
## Expected Behavior
need to delete cookies during ngOnDestroy and ngOnInit

## Actual Behavior
not deleting cookies during ngOnDestroy and ngOnInit

## Specifications

  - Version: 2.1.0
  - Browser: chrome

**Comment by CunningFatalist** [comment]
Hello there,

on first glance, this looks like an implementation issue. The service does not care about lifecycle events. You should post a question over at [StackOverflow](https://stackoverflow.com/questions/ask) and supply a little more information:

* What is the actual code you are using?
* What is the error message you are getting?
* What are your `document.cookie` values before and after using the service?

If you are sure that there's an issue with our service, please feel free to post a bug report / open another issue.

Cheers
