### ISSUE TITLE
ngx-cookie-service incompatible with Angular 8

### ISSUE THREAD

**Issue by pedrovsp** [7leads/ngx-cookie-service#70]
## Expected Behavior
Angular project should runs normally after being upgraded from Angular 7 to Angular 8.

## Actual Behavior
Project runs but with the following error:

> ERROR in ./node_modules/ngx-cookie-service/cookie-service/cookie.service.js 139:59-67
"export 'DOCUMENT' was not found in '@angular/platform-browser'

I tracked down the error and I believe this is happening because the DOCUMENT declaration was moved from the @angular/platform-browser to the @angular/core module.
This change can be see on issue [#15470 ](https://github.com/angular/angular/pull/28117) from the Angular repo.

## Steps to Reproduce the Problem
Create an Angular 8 project, add ngx-cookie-service to the project, try running the project.

## Specifications

  - Version: Angular 8
  - Browser: Chrome

**Comment by CunningFatalist** [comment]
Hello,

have you tried updating your cookie service to `^2.2.0`? We removed the `platform-browser` import in Januar 2018. 

See https://github.com/7leads/ngx-cookie-service/commit/ccee061511cfa09cebea93b9ccc562c5e8dbc4ce#diff-6ae0332c6a94366bb0368cbe628297d1

Cheers

PS: I just set up a NG8 test project just to make sure and everything worked just fine.
