### ISSUE TITLE
Setting cookie for unlimited duration not working

### ISSUE THREAD

**Issue by youngsmith1** [7leads/ngx-cookie-service#71]
## Expected Behavior
I do not want to expire cookie on browser close

## Actual Behavior
Cookie expires once browser is closed

## Steps to Reproduce the Problem
I am using below given code
this.cookieSvc.set(cookie, JSON.stringify(data), 2147483647, "/", '.somesystem.com');

I am browsing site on somesystem.com

## Specifications
  - Browser: Can be reproduced on all browsers

**Comment by youngsmith1** [comment]
This was because i was specifying a value that was too long. Expires parameter expect you to provide days. I am now passing 365 days to create cookie for 1 year.

**Comment by bergamin** [comment]
Thanks, @youngsmith1. I was looking around to see what that `expires` value meant because it is not explained in the readme
