### ISSUE TITLE
Set Cookie as JSON?

### ISSUE THREAD

**Issue by m-te** [7leads/ngx-cookie-service#72]
## Expected Behaviour

Is it possibly to set the cookie as JSON?
## Actual Behaviour

Cookie gets set as encoded text
## Specifications

  - Version: ^2.2.0
  - Browser: Chrome

Is it possible to set cookie as a JSON so it's accessible by other subdomain that uses a different package and requires cookie data in JSON format?

I tried setting object data as it is, or using JSON.parse but they all set it as Object %something% basically doesn't work

I don't know a whole lot about limitations of what's allowed and not, I did find that someone made a pull request in issues when searching JSON about setJson and getJson methods, but not sure how that would help my case where I need in stored as JSON

If it's possible please let me know

**Comment by CunningFatalist** [comment]
Hello,

sorry for the late answer, I was out of office. Questions such as this are best [asked over at StackOverflow](https://stackoverflow.com/questions/ask). You might also find [our FAQ section](https://github.com/7leads/ngx-cookie-service#faq) helpful.

Cheers
