### ISSUE TITLE
sameSite='None'

### ISSUE THREAD

**Issue by PyroFlaming** [7leads/ngx-cookie-service#76]
## Expected Behavior
set cookie with sameSite = None

https://www.chromestatus.com/feature/5633521622188032

## Specifications
  - Version: 78.0.3904.70
  - Browser: Chrome

**Comment by vora1993** [comment]
We need this ASAP as chrome new version is coming soon

**Comment by vora1993** [comment]
I also see a pr open for this issue can somebody please approve and merge that pr.

**Comment by CunningFatalist** [comment]
Hello

Thanks for reporting this and sorry for my late reply. #77 was just merged. I will publish a new version on NPM soon.

Cheers

**Comment by Yohandah** [comment]
Hello,

With ngx-cookie-service 2.4 I still have the warning in my browser's console for some reason.

> A cookie associated with a resource at http://localhost/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

Are we sure this is fixed ? Does anyone can check if they are rid of the issue ?

**Comment by PyroFlaming** [comment]
We use it already everything is working

> @CunningFatalist
> Hello,
> 
> With ngx-cookie-service 2.4 I still have the warning in my browser's console for some reason.
> 
> > A cookie associated with a resource at http://localhost/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
> 
> Are we sure this is fixed ? Does anyone can check if they are rid of the issue ?

We use it already everything is working

**Comment by Yohandah** [comment]
@PyroFlaming 
Well doing so : 
```
  this._cookieService.set(
      "loginToken",
      user.loginToken,
      "a date object"
    );
```

Results in this : 
![image](https://user-images.githubusercontent.com/15921402/76333637-3213fd80-62f2-11ea-8b1f-80717483bc35.png)

So what am I missing ?

**package.json**
`"ngx-cookie-service": "^2.4.0",`

**Comment by PyroFlaming** [comment]
@Yohandah  hope this help you.

package version: "ngx-cookie-service": "2.3.0",

this._cookieService.set(
                            cookieName,
                            cookieValue,
                            expirationDate,
                            '/',
                            someData,
                            false, <- secure flag 
                            'Lax' <- sameSite property
                        );

some information about the change and how to test it fully:

1. https://digiday.com/media/what-is-chrome-samesite/ :
What do publishers need to do in order to get ready for February?
Publishers can begin testing whether their sites are affected by going to chrome://flags and enabling #same-site-by-default-cookies and #cookies-without-same-site-must-be-secure to see whether anything breaks. They should also migrate to HTTPS secure pages, if they haven’t done so already.

2. https://web.dev/samesite-cookies-explained/

**Comment by Yohandah** [comment]
@PyroFlaming Yeah well I think your way works because you specify the secure flag manually, but it should be setted as well when using cookieService with only a key and a value !!

**Comment by joannsaeou** [comment]
login() {
  const empId = this.form.controls['empId'].value;

  this.http.get('/api/employees/' + empId).subscribe(res => {
      if (res) {
        this.cookieService.set('session_user', empId, 1);
        this.router.navigate(['/']);
      }  else {
        this.error = 'The employee ID is invalid. please try again.';
      }
  });
}


will not let me log into my own webpage.
